management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

mocou:
  lifecycle:
    expiration:
      scheduler-enabled: false
  perf:
    expiration-control-enabled: false
