spring:
  application:
    name: mocou-backend
  profiles:
    active: local
  flyway:
    locations: classpath:db/migration
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: health, info

mocou:
  lifecycle:
    expiration:
      fixed-delay-ms: 60000
      chunk-size: 1000
